Carbon:
  LinkHelper:
    externalTarget: _blank
    assetExternal: 'image,video,pdf'
    instanceOfDocument: '[instanceof Neos.Neos:Document]'
    prependIdentifier: id-

Neos:
  Neos:
    fusion:
      autoInclude:
        Carbon.LinkHelper: true
